### PR TITLE
Introduce Makefile

### PR DESCRIPTION
**Pull request by tuxofil**

### CODE REVIEW

**Comment by tuxofil** [comment]
Let me explain. AFAIK, rebar _can_ fill 'modules' info in case it is not defined yet. But Makefile recipe can not. As you see, 'compile' target does not contain 'rebar compile' and that's the goal of my patch - add ability to build project on systems without rebar, but 'make' available.
Unfortunately, rebar is not included in Erlang OTP, and building projects with strict rebar dependency forces us to install rebar manually or package it (with deb/rpm) and support this extra package.
I hope we`ll find the compromise :)

**Comment by jwilberding** [comment]
I am not sure it is unfortunate, but yes, you are right, rebar is not included with Erlang/OTP. I am not sure I agree with your solution though. I think a better way would be to have a Makefile that has a 'get-rebar' function that pulls down the correct version of rebar, compiles it, and uses it to build erlmarkdown. 

Would this approach satisfy what you need? I am not suggesting you have to write the Makefile to do it, I can take care of it, but I want to make sure first that it fulfills what you need.

**Comment by jwilberding** [comment]
@tuxofil Hey, just following up with you again, thanks!

**Comment by fisher** [comment]
perl language have its own methods to build what is needed without any package manager, python have its eggs too, erlang in a turn have a tool which helps _developers_ to deal with dependencies, but! Suddenly! There actually IS a package manager in most operating systems and we do not want a rebar tool in this case.
Makefile have a rich set of methods to compile your project without any dumb helpers like rebar, just admit it and grow up already.

**Comment by ericbmerritt** [comment]
@fisher both perl and python have library code for creating these packages which is equivalent to rebar. Its easier to install that library code because both perl and python have a decent package system and lots of native os packages for many different OSs. They have the community to be able to do that, Erlang does not. So while we may see a package system in the future equivalent to cpan, I doubt we will see any native packages any time soon. It would actually be a shame if we did, that means our small community is spending time packaging code differently for each operating system rather then doing things that actually add to the community. 

Granted, rebar is a poor build system and a worse package management system. However, its the best we have right now. Native packages + make are not an acceptable replacement. With that said @jwilberding is going to create the changes he suggested above. If you really want a make based system, I suggest you maintain a fork of this package with your changes. Its fairly easy to keep such forks up to date with git.

With that I am closing this pull request.

**Comment by jwilberding** [comment]
This is addressed in https://github.com/erlware/erlmarkdown/pull/6

**Pull request closed without merging**
